anaconda/docker-images

anaconda/Dockerfile
anaconda3/Dockerfile
miniconda/Dockerfile
miniconda3/Dockerfile

Copied from the official Python images: https://github.com/docker-library/python

Set LANG environment variable

---

scripts/conda_build_in_docker.sh

This is an example script to simplify (reproducible) conda builds from e.g. https://github.com/conda/conda-recipes
I thought it might be useful for the wider community. Let me know what you think.

Added a convenience script to reproducble run a conda build.

---

conda_builder_linux/docker_wrapper.sh

This patch does the following:
* it adds a new -I / --image option to set the docker image to be used.
* it handles '--' the canonical way, i.e. by stopping the option handling. This allows to split arguments into those directed at the 'docker' command and those for the command to be run inside the container.
* that, in turn, allows us to remove the explicit handling of options like '-e', '-v', and '--rm', which are now handled via pass-through variables.
Thus, the only user-visible change is the addition of the image option.
Oh, and by using the default '--log-driver' option handling, this requires the option to be passed via `--log-driver=foobar` rather than `--log-driver foobar`.

Add -I/--image option, as well as support for pass-through options.

---

anaconda/alpine/Dockerfile
anaconda/debian/Dockerfile
anaconda3/alpine/Dockerfile
anaconda3/debian/Dockerfile
miniconda/alpine/Dockerfile
miniconda/debian/Dockerfile
miniconda3/alpine/Dockerfile
miniconda3/debian/Dockerfile

Slim down docker image for miniconda

---

.github/workflows/miniconda_alpine_ci.yml
miniconda3/alpine/Dockerfile

Also add procps (containing ps) instead of psmisc to alpine image.

Use tags as calculated by the docker metadata action for alpine

---

.github/workflows/anaconda_pkg_build.yml

ref https://github.com/aws-actions/amazon-ecr-login/issues/116

Use the docker/login-action to login into public ECR

---

.github/shellcheck-matcher.json
.github/workflows/lint.yml
Makefile
scripts/build_anaconda.sh
scripts/conda_build_in_docker.sh

Add shell script linting with shellcheck

---

anaconda-pkg-build/linux/Dockerfile
anaconda-pkg-build/linux/entrypoint.sh

CMD should be anyway overwritten by etc concourse.

Use entrypoint script as default command

---

README.md

I'm assuming that the triple "docker docker docker" was a typo and not some inside joke or convention that I was missing :)

Update to the readme title

---

qa-images/s390x/README.md
qa-images/s390x/clefos.Dockerfile
qa-images/s390x/ubuntu.Dockerfile

Based on [anaconda-pkg-build](https://github.com/ContinuumIO/docker-images/blob/master/anaconda-pkg-build/linux/Dockerfile) with a lot of "what's this?" and `apt-cache search <...>`.
Might be cool to upload these somewhere at some point to make it easier? 🤔

QA Docker images for linux-s390x

---

.github/workflows/miniconda_alpine_ci.yml
miniconda3/alpine/Dockerfile
miniconda3/debian/Dockerfile

Last commit is related to https://github.com/conda/constructor/issues/596

Update to miniconda3-py310_22.11.1-1

---

anaconda3/amazonlinux/Dockerfile
anaconda3/debian/Dockerfile

If merged, we can tag `anaconda3-2023.03-1` to build & deploy the images.

PKG-618: Updates for AD-2023.03-1

---

anaconda3/amazonlinux/Dockerfile
anaconda3/debian/Dockerfile

Once approved and merged, we will be able to build the images for `anaconda3-2023.07-1`.

INST-12: Updates for AD-2023.07-1

---

miniconda3/alpine/Dockerfile
miniconda3/debian/Dockerfile

Once approved and merged, we will be able to build the images for `miniconda3-23.5.2-0`.

INST-179: Updates for Miniconda-23.5.2-0

---

anaconda-pkg-build-lts/linux/Dockerfile

Simply updating to the latest version to fix 2 bugs.

Update the time machine plugin in the LTS image

---

miniconda3/debian/Dockerfile

Updated `conda` version and `hashes`

Updates for Miniconda-23.9.0-0

---

miniconda3/debian/Dockerfile

Update CONDA_VERSION and hashes for `Miniconda3-23.10.0-1`.

Updates for Miniconda3-23.10.0-1

---

.github/workflows/anaconda_debian_ci.yml
.github/workflows/anaconda_pkg_build_linux.yml
.github/workflows/anaconda_pkg_build_lts_linux.yml
anaconda-pkg-base/linux/README.md
anaconda-pkg-base/linux/defaults.Dockerfile
anaconda-pkg-build/linux/Dockerfile
anaconda3/amazonlinux/Dockerfile
anaconda3/debian/Dockerfile

Simple update to docker images.

[INST-370] Update version and hashes.  Removing ppcle as it is no longer supported.

---

miniconda3/debian/Dockerfile

Updating to miniconda 24.1.2-0
Updating hashes

Updating version and hash.

---

README.md
anaconda-pkg-build/linux/Dockerfile
anaconda-pkg-build/linux/cuda/Dockerfile
anaconda3/amazonlinux/Dockerfile
anaconda3/debian/Dockerfile
miniconda3/debian/Dockerfile
renovate.json

anaconda/renovate-config now has the installer data source: https://github.com/anaconda/renovate-config/blob/main/anaconda-installers.json
Inherit from this config and simplify the documentation.

Use anaconda-installers preset from anaconda/renovate-config
