anaconda/docker-images

anaconda/Dockerfile
anaconda3/Dockerfile
miniconda/Dockerfile
miniconda3/Dockerfile

Now that repo.continuum.io has an HTTPS endpoint (should be the default), switch to using it. Fixes #3.

wget from the HTTPS endpoint of repo.continuum.io

---

anaconda/Dockerfile
anaconda3/Dockerfile
miniconda/Dockerfile
miniconda3/Dockerfile

See this for a brief explanation of `tini` and its purpose ( https://github.com/docker-library/official-images#init ). For more information about `tini` and its source code ( https://github.com/krallin/tini ). For more in depth information about the reaping problem and why it is a problem ( https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/ ).

Use tini as PID 1 (solve the reaping problem)

---

conda_builder_linux/CHANGELOG
conda_builder_linux/Dockerfile
conda_builder_linux/build/alias_32bit.sh
conda_builder_linux/build/internal_startup.sh

cc @dsludwig @PeterDSteinberg - this adds your sudo fix, plus makes output only show up if the run script is not passed any build command.  Please let me know if this solves your issues.
Also, word of advice: if you pass --rm to the run script, then the docker container will clean itself up and remove itself when it's done.  You probably want that, if you don't already do something to clean them up.  They will otherwise build up over time and needlessly consume disk space.

conda_builder_linux: optionally silence output, create output folders

---

centos5_gcc5_base/Dockerfile
centos5_gcc5_base/symlink_libraries.sh
conda_builder_linux/Dockerfile

Compress filesize thanks to @dsludwig suggestion by moving chmod up to earlier run section.  Also fixes some errors seen because of system libraries in /usr/lib being the old versions.  Symlinks new versions to replace them.

builder: save size; symlinks in /usr/lib*

---

README.md
anaconda/Dockerfile
anaconda/README.md
anaconda3/Dockerfile
anaconda3/README.md
miniconda/Dockerfile
miniconda/README.md
miniconda3/Dockerfile
miniconda3/README.md

* Update to Debian 8.5 base image
* Add Jupyter notebook installation and startup
* Remove unused libraries/commands
* Update description and usage in README
@mutirri, can you review these changes? We can iterate on this image first, then I can update the other images (anaconda, anaconda3, miniconda). Note that the updated base image and removed libraries were based on the results of the [Docker security scan](https://docs.docker.com/docker-cloud/builds/image-scan/).

Update Docker images/README

---

miniconda3/Dockerfile

This does the following:
1.  Remove listed maintainer
2.  Remove a few of the apt packages, also clear lists
3.  Update miniconda to 4.3.31
4.  Call `conda clean -tipsy` at the end of the conda line
5.  Replace TINI dpkg installation with solution suggested here:
https://github.com/krallin/tini#using-tini
This is untested and includes removing some packages.  This is up here for review.

Update miniconda3 Dockerfile

---

anaconda/Dockerfile
anaconda3/Dockerfile
miniconda/Dockerfile
miniconda3/Dockerfile

fix #81 
Also switch to `debian:latest`.

 fix #81 activate conda base environment

---

README.md
scripts/build_anaconda.sh

Right now the build script is hardcoded to go to the continuumio docker hub. This abstracts out this to the default there, but if you utter
```
cd scripts
bash build_anaconda.sh -v 2019.03 -r tongfamily
```
Then it will automatically tag things it `tongfamily` as the Docker repo namspace instead. This is useful for folks who want to do a full fork and have a stable build

build_anaconda abstracts out continuumio as the repo name

---

conda_ci/conda-ci-linux-64-python2.7/Dockerfile
conda_ci/conda-ci-linux-64-python3.7/Dockerfile
conda_ci/conda-ci-linux-64-python3.8/Dockerfile

Now have version parity for `codecov` and `radon`, so there's really no reason to continue installing these packages from PyPI.

Update CI images to install packages from defaults

---

miniconda3/debian/Dockerfile

The images are tagged with a Conda version so we should specify that version when we install it.
This also allows us to trigger a build based on changing the version

Pin Miniconda3 to a specific version

---

.github/workflows/ci.yml

This allows to on-demand re-build the conda-ci-linux-64-python* containers

Allow manual workflow trigger via GitHub UI

---

.github/workflows/ana_pkg_build_cicd.yml
anaconda-pkg-build/linux/Dockerfile

Dockerfile + CI/CD files to generate images used by Anaconda Inc. to build conda packages for the defaults channel.

Docker images for Anaconda's package building team

---

.github/workflows/miniconda_debian_ci.yml
miniconda3/debian/Dockerfile

Also removes the unintentional shell overwrite from miniconda debian image, which was not published yet.

Fix miniconda debian push condition

---

anaconda3/debian/Dockerfile
miniconda3/debian/Dockerfile

The addition of the --no-install-recommends switch to apt-get removed some
implicitly added packages.
Explicitly re-adding ssh as it is a common requirement, when using the
docker image on CI systems.
Also do shasum checking without pipe to not mask errors.
closes: https://github.com/ContinuumIO/docker-images/issues/218

Explicitly add openssh-client

---

.github/workflows/miniconda_debian_ci.yml

This should result into:
| Event           | Ref                           | Docker Tags                         |
|-----------------|-------------------------------|-------------------------------------|
| `pull_request`  | `refs/pull/2/merge`           | `pr-2`                              |
| `push`          | `refs/heads/master`           | `master`                            |
| `push tag`      | `refs/tags/miniconda3-v1.2.3`            | `v1.2.3`, `latest`                  |
| `push tag`      | `refs/tags/miniconda3-v2.0.8-beta.67`    | `v2.0.8-beta.67`, `latest`          |
So *latest* points to latest tagged image, *master* points to latest upload from push to master. 
While git tags propagate to docker image tags, they don't yet propagate into the image by influencing which …

Add tagging support for miniconda3 debian image

---

anaconda3/debian/Dockerfile
miniconda3/debian/Dockerfile

This removes the warning during build:
"miniconda.sh: 27: miniconda.sh: ps: not found"

Add procps providing /bin/ps

---

.github/dependabot.yml
.github/workflows/ana_pkg_build_cicd.yml
.github/workflows/anaconda_alpine_ci.yml
.github/workflows/anaconda_debian_ci.yml
.github/workflows/conda_ci_cicd.yml
.github/workflows/lint.yml
.github/workflows/miniconda_alpine_ci.yml
.github/workflows/miniconda_debian_ci.yml

Github action versions are derived from git tags as actions are just cloned as repos and used during flows.
But tags can be deleted and republished with malicious code, whereas a commit at a specific hash is immutable.
Dependabot helps to keep the non-human-readable sha1 pinned versions up-to-date by providing update PRs with changelogs.

Secure github actions via immutable sha1s instead of version tags

---

.github/workflows/miniconda_alpine_ci.yml
miniconda3/alpine/Dockerfile

Also update:
* The Alpine base image to 3.14.0 and glibc to 2.33-r0
* The Github action to push the image
* Switch to bash as ash is not fully supported by conda and add psmisc

Update Miniconda3 alpine to 4.10.3

---

anaconda3/README.md
miniconda3/README.md

* Adding -p helps of container restarts
* --allow-root is required since a while, as there currently is no user setup in the container
* Referencing Python 3.X to make the README more generic for further updates.
* Updating installer download page URLs

Update docker jupyter example command and Python version in READMEs

---

anaconda3/debian/Dockerfile
miniconda3/debian/Dockerfile

Debian 11 bullseye was released on 2021-08-14:
https://www.debian.org/News/2021/20210814
Merging this to master results in a new container upload with tag `master`, which allows testing the created image before the next version tagged release.

Upgrade to bullseye for Debian based containers

---

.github/workflows/concourse_rsync_resource.yml
.gitmodules

Use the repo to publish the concourse-rsync-resource via github actions, as the logic + secret is in common with the other workflows.

Publish concourse-rsync-resource via github actions

---

.github/workflows/anaconda_pkg_build.yml

Currently, our version of Concourse is struggling with the manifest list v2. 😞 
To alleviate that, we can try building an image from the same Dockerfile as the `anaconda-pkg-build` only for **linux/amd64**. The meta and steps are similar but it has a new name: `concourse-pkg-build`. This should put a sole manifest & image into ECR, similar to `concourse-rsync-resource`
I am open to thoughts on alternatives or other options to get a single image manifest in ECR. I was not sure if we could tag one platform specifically, i.e.,:
> public.ecr.aws/<...>/anaconda-pkg-build:linux-64

Add Concourse specific build image.

---

anaconda-pkg-build/linux/Dockerfile

`tar` is currently available on all linux images aside from **linux-aarch64** (amazonlinux). So, make it explicit include `/usr/bin/tar`.
As far as I know, we currently do not provide `tar` in **defaults**. That would be the other option.
Suggesting this as it is causing [git-feedstock](https://github.com/AnacondaRecipes/git-feedstock/pull/7)'s build to fail.

Add tar to the build image.

---

miniconda3/alpine/Dockerfile

Allows building and uploading an updated image just by tagging a new release (as it is possible for the other images).
fixes: https://github.com/ContinuumIO/docker-images/issues/261

Unpin Miniconda alpine release updates

---

anaconda-pkg-build/linux/Dockerfile

Let me know, if you'd prefer a different solution, but we do have packages that use OpenGL (e.g. VTK) and need libOpenGL.so.* around during testing.

Install libglvnd-opengl to have libOpenGL.so.* available

---

miniconda3/debian/Dockerfile

If merged, we can tag `miniconda3-v4.12.0` to build & deploy the images.

DSNC-4587: Miniconda-4.12.0 docker images

---

anaconda3/amazonlinux/Dockerfile
anaconda3/debian/Dockerfile

If merged, we can tag `anaconda3-2022.05` to build & deploy the images.

DSNC-4587: Anaconda Distribution 2022.05 docker images

---

anaconda-pkg-build/linux/Dockerfile

The `GCC_VER` arg only has influence on what is cached by the container to achieve faster builds. What is really used during a build is fully defined by the feedstock/cbc.yaml.
See also: https://github.com/AnacondaRecipes/aggregate/blob/master/conda_build_config.yaml#L52

Update cached gcc version to 11.2.0 to be in line with aggregate/cbc.yaml

---

anaconda3/amazonlinux/Dockerfile
anaconda3/debian/Dockerfile

If merged, we can tag `anaconda3-2022.10` to build & deploy the images.

PKG-72: Anaconda Distribution 2022.10 docker images

---

anaconda-pkg-build/linux/Dockerfile

We anyway already call `conda update --all` in the Dockerfile, so this PR should not change that much, besides starting from an less old miniconda3.

Update Miniconda in pkg-build container to py39_23.1.0-1 + enable libmamba solver

---

anaconda-pkg-build/linux/Dockerfile

This hopefully is the last attempt to enable libmamba as solver:
* It was initially enabled via https://github.com/ContinuumIO/docker-images/pull/350
* Then setting the solver was done after clean to avoid incompatible cache meta data https://github.com/ContinuumIO/docker-images/pull/355 and https://github.com/ContinuumIO/docker-images/pull/356
The container created from current master branch still fails on s390x:
```docker run -ti --rm --platform linux/s390x continuumio/anaconda-pkg-build:master /bin/bash -c "conda install numpy"``` with `RuntimeError: Could not read JSON repodata file (/opt/conda/pkgs/cache/8943ae43.json) parse error line 1`
But is successful with ```docker run -ti --rm --platform linux/s390x continuumio/anaconda-pkg-build:master /bin/bash -c "conda clean --index-cache …
```

Delete index-cache at the end of container creation

---

miniconda3/debian/Dockerfile

If merged, we can tag `miniconda3-v23.3.1-0` to build & deploy the images.

PKG-1811: Updates for Miniconda-23.3.1-0

---

.github/workflows/anaconda_pkg_build_lts_linux.yml

see also https://github.com/ContinuumIO/docker-images/blob/main/.github/workflows/anaconda_pkg_build_linux.yml#L86

Disable latest tag for lts container

---

anaconda-pkg-base/linux/README.md
anaconda-pkg-base/linux/defaults.Dockerfile
anaconda-pkg-base/linux/ubuntu.Dockerfile

Identiacally to the anaconda-pkg-build image, but without miniconda3 pre-installed. This allows testing of miniconda3/anaconda3/other installers including testing conda-build.
This is based on the previous s390x only qa image, we can be found in the [repo history](https://github.com/ContinuumIO/docker-images/tree/912aa2402e807e2faeaf1e778c6be7cd73e70e1f/qa-images/s390x)

Add anaconda-pkg-base image

---

.github/workflows/anaconda_pkg_build_linux_cuda.yml
anaconda-pkg-build/cuda/linux-64/Dockerfile
anaconda-pkg-build/linux/cuda/Dockerfile

This is almost the same as the anaconda-pkg-build container, but derived from Nvidia's CentOS 7 CUDA 11.8.0 image.
See comment in the Dockerfile for info on what it contains and what conda must provide.
This is a copy over of [this](https://github.com/anaconda-distribution/distro-incubator/blob/dpetry-ansible-cuda-updates/rmartins/ansible-cuda/docker/Dockerfile) file which has already been used to successfully build CUDA packages.

Add Dockerfile for CUDA 11.8.0

---

anaconda-pkg-build/linux/Dockerfile
anaconda-pkg-build/linux/cuda/Dockerfile

This also removes the manual libmamba steps as libmambda became default with conda 23.10.0.

anaconda-pkg-build: Switch to miniconda 23.10.0-1

---

renovate.json

The PR titles from renovate contain `custom.miniconda`. `commitMessageTopic` should change this to the group name instead.

Use group name in PR titles

---

.github/dependabot.yml

This avoids duplicated PRs and renovate anyways handles more updates than dependabot.

Disable dependabot in favour of renovate

---

anaconda3/debian/Dockerfile
miniconda3/debian/Dockerfile

bullseye = Debian 11
bookworm = Debian 12
Renovate does not propose upgrades from bullseye to bookworm as it cannot know what is newer. With the switch to 11.9-slim it should be able to propose the update to 12.5-slim.

Change Debian tags from bullseye-slim to 11.9-slim to be renovate managed

---

.github/workflows/anaconda_pkg_build_linux.yml
.github/workflows/anaconda_pkg_build_linux_cuda.yml

Since these images keep failing to build due to CentOS 7 being EOL, disable them until a solution has been found by the package building team(s).

Disable pkg-build image builds

---

.github/workflows/anaconda_amazonlinux_ci.yml
.github/workflows/anaconda_debian_ci.yml
.github/workflows/anaconda_pkg_build_linux.yml
.github/workflows/anaconda_pkg_build_linux_cuda.yml
.github/workflows/miniconda_debian_ci.yml

The Amazon Linux builds appear to have random seg faults and other errors when installing dependencies. A possible cause is the `setup-qemu` action because it uses v7 instead of v8.

Use QEMU v8.1.5

---

anaconda-pkg-build/linux/alma/Dockerfile

This change impacts on Anaconda's CI, which currently assumes that the docker container's conda-build builds tarballs.
Here's the versions of conda-related packages in this container:
```
anaconda-anon-usage       0.5.0           py312hfc0e8ea_100    defaults
conda                     24.1.2          py312h06a4308_0    defaults
conda-build               24.1.2          py312h06a4308_0    defaults
conda-content-trust       0.2.0           py312h06a4308_1    defaults
conda-index               0.5.0           py312h06a4308_0    defaults
conda-libmamba-solver     25.1.1             pyhd3eb1b0_0    defaults
conda-package-handling    2.4.0           py312h06a4308_0    defaults
conda-package-streaming   0.11.0          py312h06a4308_0    defaults
```
here are the ones in the existing (main) …

Constrain conda build to a version which builds tarballs by default

---

anaconda-pkg-build/linux/cuda-rocky8/Dockerfile

The reason for this was because a higher glibc version was required compared with the existing cuda docker container.
This dockerfile was used to build a container that was used to build pytorch 2.5.1 linux cuda variant. This PR is to merge this for provenance. It doesn't include a github action to build and upload the container, as it's not publicly needed yet.
Rocky was chosen among the[ available platforms](https://hub.docker.com/r/nvidia/cuda/tags?name=12.4.1) because it resulted in less  adaptation needed from the current cuda recipe compared with ubi, and was more lightweight than ubuntu. v8 was chosen over v9 because it had a lower glibc version and I didn't need the later one.

Add dockerfile for rocky8 based cuda container, which supports cudnn 9.1.1

---

anaconda-pkg-build/linux/rocky8/Dockerfile

Updated conda configuration to include `defaults` channel, turn off error reporting, and ensure package format stays `.tar.bz2`.

Add package format to .condarc
